"""Generate a human-readable Markdown report tying the numbers to the figures."""

from __future__ import annotations

import math
from pathlib import Path

from .config import Config
from .runner import RunResult


def _fmt(x, n=4):
    if x is None:
        return "—"
    if isinstance(x, float):
        if not math.isfinite(x):
            return "∞" if x > 0 else "−∞"
        return f"{x:.{n}g}"
    return str(x)


def _check(ok: bool) -> str:
    return "✅ pass" if ok else "⚠️ exceeded"


def write_report(result: RunResult, cfg: Config, summary: dict, spectra: dict,
                 figures: list[tuple[str, Path]], outdir: Path) -> Path:
    outdir = Path(outdir)
    cons = summary["conservation"]
    chaos = summary["chaos"]
    meta = summary["meta"]
    L = []
    a = L.append

    a(f"# Simulation report — `{cfg.run.name}`\n")
    a(f"*{meta['n_bodies']} bodies · integrator `{meta['integrator']}` · "
      f"dt = {meta['dt_days']} d · GR `{meta['gr_mode']}` · "
      f"J2 {'on' if meta['j2'] else 'off'}*\n")
    a(f"Integrated to **{_fmt(meta['t_reached_years'])} yr** "
      f"({meta['n_samples']} samples). Status: **{meta['status']}**.\n")

    # Conservation
    a("\n## Conservation diagnostics\n")
    a("| quantity | max relative drift | tolerance | result |")
    a("|---|---|---|---|")
    a(f"| Energy $|\\Delta E/E_0|$ | {_fmt(cons['max_dE_rel'])} | "
      f"{_fmt(cons['energy_tol'])} | {_check(cons['energy_ok'])} |")
    a(f"| Ang. momentum $|\\Delta L/L_0|$ | {_fmt(cons['max_dL_rel'])} | "
      f"{_fmt(cons['angmom_tol'])} | {_check(cons['angmom_ok'])} |")
    a(f"\nAngular-momentum deficit (AMD): initial {_fmt(cons['amd_initial'])}, "
      f"final {_fmt(cons['amd_final'])}, max {_fmt(cons['amd_max'])} "
      f"(growth ×{_fmt(cons['amd_growth'],3)}).\n")

    # Chaos
    a("\n## Chaos indicators\n")
    if chaos.get("megno_enabled"):
        a(f"- **MEGNO** ⟨Y⟩ (final): **{_fmt(chaos['megno_final'],4)}** "
          f"→ classified *{chaos['classification']}* "
          f"(⟨Y⟩→2 regular, ≳4 chaotic).")
        a(f"- Lyapunov time (running estimate): {_fmt(chaos['lyap_time_years_running'])} yr; "
          f"(MEGNO-slope estimate): {_fmt(chaos['lyap_time_years_slope'])} yr.")
        if not chaos.get("diagnosis_converged"):
            a(f"- ⚠️ *Run length ({_fmt(meta['t_reached_years'])} yr) is short compared to "
              f"the ~{_fmt(chaos['reference_lyap_time_years'])} yr inner-system Lyapunov "
              f"time; MEGNO needs ≳ tens of Myr to firmly diagnose chaos. For a 1-Myr run, "
              f"⟨Y⟩≈2 is expected even though the system is formally chaotic.*")
    else:
        a("- MEGNO disabled for this run.")

    # Per-planet statistics
    a("\n## Per-planet statistics\n")
    a("| planet | a₀ [AU] | e mean | e min | e max | e range | i mean [°] | i max [°] |")
    a("|---|---|---|---|---|---|---|---|")
    for r in summary["planets"]:
        a(f"| {r['planet']} | {_fmt(r['a_init_AU'],6)} | {_fmt(r['e_mean'])} | "
          f"{_fmt(r['e_min'])} | {_fmt(r['e_max'])} | {_fmt(r['e_range'])} | "
          f"{_fmt(r['inc_mean'])} | {_fmt(r['inc_max'])} |")

    # Secular spectrum peaks
    if spectra.get("available") and spectra.get("g"):
        a("\n## Secular frequencies (FFT peaks)\n")
        a(f"FFT frequency resolution ≈ {_fmt(spectra.get('resolution_arcsec_yr'),3)} ″/yr. "
          f"Dominant perihelion-precession peak per planet vs. the Laskar reference "
          f"$g_i$ (″/yr):\n")
        a("| planet | measured peak [″/yr] | nearest reference |")
        a("|---|---|---|")
        from . import constants
        for name in result.planet_names:
            sp = spectra["g"].get(name)
            if not sp or sp["peak"] is None:
                continue
            peak = sp["peak"]
            nearest = min(constants.SECULAR_G.items(), key=lambda kv: abs(kv[1] - peak))
            a(f"| {name} | {_fmt(peak,4)} | {nearest[0]} = {nearest[1]} |")

    # Figures
    a("\n## Figures\n")
    for title, path in figures:
        rel = Path(path).relative_to(outdir) if outdir in Path(path).parents else Path(path).name
        a(f"### {title}\n\n![{title}]({rel})\n")

    a("\n---\n*Generated by the CEAM Solar-System chaos framework "
      "(REBOUND + REBOUNDx).*\n")

    report_path = outdir / "report.md"
    report_path.write_text("\n".join(L))
    return report_path
